### ISSUE TITLE
Starting the reader

### ISSUE THREAD

**Issue by TheVolatileV** [TheVolatileV/ComicReader#6]
Start working with Picasso to determine if it will work for our reader.

**Comment by TheVolatileV** [comment]
Check into ZingBox for what kind of features we will want to implement for our reader.

**Comment by ghost** [comment]
I am waiting on my new laptop to arrive NLT 09FEB17 so that I may delve into Picasso & begin developing. The suspense date for my next pull request will be 12AM on 10FEB17.

**Comment by ghost** [comment]
ReaderActivity.java compiles and functions. About 2-3 lines of code would have to be replaced in order to display images from URLs instead of local resources.
